name: Pipeline de Seguridad DevSecOps

on:
  push:
    branches: ["main"]
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 1️⃣ Obtener código del repositorio
        uses: actions/checkout@v4

      - name: 2️⃣ Verificar que index.html no esté vacío
        run: test -s index.html

      - name: 3️⃣ Instalar Snyk CLI
        run: npm install -g snyk

      - name: 4️⃣ Ejecutar análisis Snyk y guardar reporte
        id: snyk_test
        run: |
          snyk auth $SNYK_TOKEN

          # Ejecutar escaneo (agrega --file= si tienes package.json u otro)
          snyk test --json > snyk-report.json || true

          echo "===== RESUMEN SNYK ====="
          echo "Vulnerabilidades por severidad:"
          jq -r '[.vulnerabilities[]?.severity] | group_by(.) | map({(.[0]): length}) | add // {}' snyk-report.json

          critical_count=$(jq '[.vulnerabilities[]?.severity] | map(select(.=="critical")) | length' snyk-report.json)
          high_count=$(jq '[.vulnerabilities[]?.severity] | map(select(.=="high")) | length' snyk-report.json)

          echo "Critical: $critical_count"
          echo "High: $high_count"

          echo "::set-output name=critical::$critical_count"
          echo "::set-output name=high::$high_count"

          echo ""
          echo "Listado resumido:"
          jq -r '.vulnerabilities[]? | "\(.severity | ascii_upcase) | \(.title) | \(.packageName // "N/A")"' snyk-report.json

        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

      - name: 5️⃣ Subir reporte como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: snyk-report
          path: snyk-report.json

      - name: 6️⃣ Fallar si hay vulnerabilidades críticas o muchas altas
        if: always()
        run: |
          crit=${{ steps.snyk_test.outputs.critical }}
          high=${{ steps.snyk_test.outputs.high }}
          echo "Evaluando política: critical=$crit, high=$high"
          if [ "$crit" -gt 0 ] || [ "$high" -gt 5 ]; then
            echo "❌ Vulnerabilidades críticas detectadas. Abortando pipeline."
            exit 1
          else
            echo "✅ Sin vulnerabilidades críticas. Continuamos."
          fi

      - name: 7️⃣ Comentar resultado en PR (si aplica)
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        env:
          CRIT: ${{ steps.snyk_test.outputs.critical }}
          HIGH: ${{ steps.snyk_test.outputs.high }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const crit = process.env.CRIT;
            const high = process.env.HIGH;
            const body = `🧪 **Resultado Snyk**  
            - Critical: ${crit}  
            - High: ${high}  
            (pipeline ejecutado automáticamente)`;
            github.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body
            });
