name: Pipeline Completo de DevSecOps

on: 
  push:
    branches: ["main"]

jobs:
  # Trabajo 1: Verificar el código fuente
  test-source-code:
    runs-on: ubuntu-latest
    steps:
      - name: 1. Obtener código de repositorio
        uses: actions/checkout@v4

      - name: 2. Verificar que index.html no esté vacío
        run: test -s index.html
      
      - name: 3. Escanear el código en busca de vulnerabilidades (SAST)
        # --- CORRECCIÓN AQUÍ (Usando una versión etiquetada) ---
        uses: snyk/actions/cli@0.4.0 
        continue-on-error: true # No fallamos el build, solo reportamos
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: code test
          args: index.html 

  # Trabajo 2: Construir y escanear la imagen Docker
  build-and-scan-image:
    needs: test-source-code 
    runs-on: ubuntu-latest
    steps:
      - name: 1. Obtener código de repositorio
        uses: actions/checkout@v4

      - name: 2. Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 3. Construir imagen de Docker
        uses: docker/build-push-action@v5
        with:
          context: .
          tags: mi-proyecto-web:latest
          load: true

      - name: 4. Escanear imagen de Docker con Snyk
        # --- CORRECCIÓN AQUÍ (Usando una versión etiquetada) ---
        uses: snyk/actions/cli@0.4.0
        continue-on-error: true
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          command: container test
          args: --file=Dockerfile mi-proyecto-web:latest